title: my first page with jekyll
author: SureImNotSure
email: foo@bar.com
description: > # this means to ignore newlines until "baseurl:"
  this is my very first page with jekyll.
  a course from github lab learning lab.

# social links
twitter_username: none
github_username:  SureImNotSure

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
